### ISSUE TITLE
wrong jail.conf format for openmediavault-fail2ban 5.0

### ISSUE THREAD

**Issue by mariusft** [OpenMediaVault-Plugin-Developers/openmediavault-fail2ban#25]
Seems default jail.conf file has a typo when declaring jailing rules.

configuration should have "enabled =" instead of "enable =" in jail.conf

as enhancement any new parameters should go to jail.local or even better for each additional configuration separate file can be created in jail.d/ as for filters

**Comment by ryecoaaron** [comment]
Fixed in 5.0.1 which I just pushed to the repo.  I just committed the code changes for the 5.x plugin since I didn't realize I didn't push those to github.

As for the enhancement, I don't think that would be hard to put each jail in separate file in jail.d.  I don't use this plugin so it is a bit hard for me to test.

**Comment by ryecoaaron** [comment]
Using a separate file for each jail was easier than I thought and it the proper way to do it.  I also found a couple of bugs while doing this.  5.0.2 is in the repo now.
